version: '3'

services:
  # Database
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysqlTest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - mysql-test-network
    container_name: MySql-root-root
    ports:
      - '3306:3306'
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: mysql-phpadmin
    restart: always
    ports:
      - '80:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mysql-test-network
    container_name: phpMyAdmin-user-root
  
networks:
  mysql-test-network:
volumes:
  db_data: