// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySqlBlazorApp.Data;

namespace MySqlBlazorApp.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210206100402_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MySqlBlazorApp.Models.Enfant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<int>("FamilleId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamilleId");

                    b.ToTable("Enfant");
                });

            modelBuilder.Entity("MySqlBlazorApp.Models.Famille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomDeFamille")
                        .HasColumnType("text");

                    b.Property<int>("Qf")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Famille");
                });

            modelBuilder.Entity("MySqlBlazorApp.Models.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<string>("Cp")
                        .HasColumnType("text");

                    b.Property<int>("FamilleId")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.Property<string>("Tel")
                        .HasColumnType("text");

                    b.Property<string>("Ville")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamilleId");

                    b.ToTable("Parent");
                });

            modelBuilder.Entity("MySqlBlazorApp.Models.Enfant", b =>
                {
                    b.HasOne("MySqlBlazorApp.Models.Famille", "Famille")
                        .WithMany("Enfants")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MySqlBlazorApp.Models.Parent", b =>
                {
                    b.HasOne("MySqlBlazorApp.Models.Famille", "Famille")
                        .WithMany("Parents")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
